app = "ink-analyzer-rh-01"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  INK_SAFE = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
